Первая итерация
ironhird/GO-Yandex-Practicum-sprint-5 pull request #1
Opened 2024-10-25 02:46 UTC by ironhird

2024-10-25 12:52 UTC, just-musha requested changes
Привет! Неплохая работа, основное сделано верно. Верну в основном чтобы проверить формулу. И работа будет принята!

2024-10-25 12:52 UTC, just-musha commented on main.go
> +	return t.distance() / t.Duration.Hours()
Здесь нужно не забыть добавить проверку на 0 перед делением, как было в 4 спринте

Давай ниже по коду тоже сразу добавим, там где это нужно

2024-10-25 12:52 UTC, just-musha commented on main.go
> +	result := float64(CaloriesMeanSpeedMultiplier)*r.meanSpeed() + CaloriesMeanSpeedShift
Хороший подход разбить сложные вычисления на отдельные переменные

2024-10-25 12:52 UTC, just-musha commented on main.go
> +	result := CaloriesWeightMultiplier*w.Weight + (math.Pow(w.meanSpeed(), 2)/w.Height)*CaloriesSpeedHeightMultiplier*w.Weight
Стотит проверить формулу. Все ли значения приведены к нужным единицам измерения. Сейчас есть сомнения насчет Height

Должно получиться 947.82

2024-10-25 12:52 UTC, just-musha commented on main.go
> +		TrainingType: "Плавание",
Плохая практика - использовать захардкоженные значения в коде
Тут лучше тоже взять значение из структуры `s`

2024-10-25 14:26 UTC, ironhird commented on main.go
> +	return t.distance() / t.Duration.Hours()
Добавил везде проверку на 0 перед делением

2024-10-25 14:26 UTC, ironhird commented on main.go
> +	result := float64(CaloriesMeanSpeedMultiplier)*r.meanSpeed() + CaloriesMeanSpeedShift
Разбил сложные вычисления на отдельные переменные

2024-10-26 00:25 UTC, ironhird commented on main.go
> +	result := CaloriesWeightMultiplier*w.Weight + (math.Pow(w.meanSpeed(), 2)/w.Height)*CaloriesSpeedHeightMultiplier*w.Weight
Перевел Height в метры, добавил константу из спринта 4:
kmhInMsec = 0.278 // коэффициент для преобразования км/ч в м/с.
и перевел скорость в метры/сек. Получил 947.82

2024-10-26 00:29 UTC, ironhird commented on main.go
> +		TrainingType: "Плавание",
Заменил на значение из структуры.

2024-10-26 10:24 UTC, just-musha approved these changes
Супер! Спасибо за комменты по изменениям, очень удобно проверять. Небольшую рекомендацию к организации проверок оставила, не крит. Принято!

2024-10-26 10:24 UTC, just-musha commented on main.go
> +	if t.Duration.Hours() > 0 {
Небольшая рекомендация по стилю (здесь не критично)

Обычно проверки чуть по другому делают: сначала проверяют не стандартные случаи (их мб несколько), и в конце остается базовый с формулой:

```
if t.Duration == 0 {
    return 0
}

 if <еще какая-то провера> {
    return ...
}

return <тут уже формула>
```

2024-10-28 03:51 UTC, merged